---
control_node:
  hosts:
    localhost:
      roles:
        - certificate_authority
ubuntu:
  hosts:
    external_attacker:
      ansible_host: 192.168.1.55
      roles:
        - common
        - docker
    dmz_hosting:
      ansible_host: 10.1.0.162
      roles:
        - common
        - docker
    internal_ubuntu_server:
      ansible_host: 10.2.0.110
      roles:
        - common
windows:
  hosts:
    management_dc01:
      ansible_host: 10.1.0.20
      roles:
        - common
    internal_win11_protected:
      ansible_host: 10.2.0.5
      roles:
        - common
    internal_win11_unprotected:
      ansible_host: 10.2.0.6
      roles:
        - common
    internal_win10_protected:
      ansible_host: 10.2.0.7
      roles:
        - common
    
