---


- name: Create server key
  command: >
    openssl genrsa -out ./certs/server-key.pem 4096


- name: Create server CSR
  command: >
    openssl req -subj '/CN=aaf01' -sha256 \
    -new -key ./certs/server-key.pem \
    -out ./certs/server.csr


- name: Remove extfile
  file:
    state: absent
    path: "./certs/extfile.cnf" 

- name: Create extfile
  file:
    state: touch 
    path: "./certs/extfile.cnf"

- name: Add alt name to extfile
  lineinfile:
    dest: "./certs/extfile.cnf"
    line: "subjectAltName = {{ docker_subjectAltName }}"

- name: Create server certificate
  command: >
    openssl x509 -req -days 365 -sha256 -in ./certs/server.csr \
    -CA ./certs/ca.pem \
    -CAkey ./certs/ca-key.pem \
    -CAcreateserial -out ./certs/server-cert.pem \
    -extfile ./certs/extfile.cnf \
    -passin pass:{{ privatekey_passphrase }}
