---
- name: Update and upgrade Ubuntu machines
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Change DNS server
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 10.1.1.53'
    state: present

- name: Download Debian package on Ubuntu
  ansible.builtin.get_url:
    url: https://example.com/path/to/package.deb
    dest: /tmp/package.deb
    mode: '0644'


- name: Install Debian package on Ubuntu
  ansible.builtin.apt:
    deb: /tmp/package.deb