---
- name: Main playbook to call sub-playbooks for Ubuntu and Windows
  hosts: all
  become: yes
  tasks:
    - name: Include Ubuntu baseline playbook
      include_tasks: ubuntu_baseline.yml
      when: ansible_os_family == "Debian"

    - name: Include Ubuntu Docker playbook
      include_tasks: ubuntu_docker.yml
      when: (ansible_os_family == "Debian") and (tags == "hosting_server")



    - name: Include Windows baseline playbook
      include_tasks: windows_baseline.yml
      when: ansible_os_family == "Windows"
