---
ansible_user: "{{ windows_user }}"
ansible_password: "{{ windows_password }}"
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5986